apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - cephcluster.yaml
  - monitoring-rbac.yaml
  - prometheus-rules.yaml
  - postsync-ceph-health-rbac.yaml
  - postsync-ceph-health.yaml
