apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/cnp-argocd.yaml
  - monitoring/cnp-monitoring.yaml
  - rook-ceph/cnp-rook-ceph.yaml
  - ceph-clients/cnp-ceph-clients.yaml
  - tracing/cnp-tracing.yaml
