apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: rgw-degradation
  namespace: rook-ceph
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - rook-ceph
    labelSelectors:
      app: rook-ceph-rgw
  loss:
    loss: "30"
    correlation: "25"
  duration: "30m"
